name: SlimefunExtension
version: '${project.version}'
main: net.guizhanss.slimefunextension.SlimefunExtension
api-version: 1.16
authors: [ ybw0014 ]
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
description: A Slimefun Addon
