name: SlimefunExtension
version: '${project.version}'
main: net.guizhanss.slimefunextension.SlimefunExtension
api-version: 1.16
depend: [ Slimefun ]
softdepend: [ GuizhanLibPlugin ]
authors: [ ybw0014 ]
description: A Slimefun Addon
